import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";
import { sections } from "./sections";

const sidebars: SidebarsConfig = Object.fromEntries(
  sections.map((section) => [
    section.id,
    [{ type: "autogenerated" as const, dirName: section.id }],
  ]),
);

export default sidebars;
